using ABB.Analyze.VisualStudio.Models;
using System.Text;

namespace ABB.Analyze.VisualStudio.Services;

internal static class PrDescriptionService
{
    public static string Generate(
        DashboardModel model,
        MutationSummary? mutation)
    {
        var output = new StringBuilder();

        output.AppendLine("## Summary");
        output.AppendLine();
        output.AppendLine(model.Summary);
        output.AppendLine();

        output.AppendLine("## Risk");
        output.AppendLine();
        output.AppendLine($"**{model.Risk}**");
        output.AppendLine();

        if (model.Reasons.Count > 0)
        {
            output.AppendLine("## Impact and Review Notes");
            output.AppendLine();
            foreach (string reason in model.Reasons)
            {
                output.AppendLine($"- {reason}");
            }
            output.AppendLine();
        }

        if (model.AffectedFiles.Count > 0)
        {
            output.AppendLine("## Affected Files");
            output.AppendLine();
            foreach (string file in model.AffectedFiles)
            {
                output.AppendLine($"- `{file}`");
            }
            output.AppendLine();
        }

        output.AppendLine("## Test Guidance");
        output.AppendLine();
        if (model.Tests.Count == 0)
        {
            output.AppendLine("- No test guidance was returned.");
        }
        else
        {
            foreach (TestRow test in model.Tests)
            {
                string detail = string.IsNullOrWhiteSpace(test.TestOrCommand)
                    ? test.SourceFile
                    : test.TestOrCommand;

                output.AppendLine(
                    $"- **{test.DisplayStatus}:** `{detail}` — {test.Recommendation}");
            }
        }
        output.AppendLine();

        if (mutation != null)
        {
            output.AppendLine("## Mutation Testing");
            output.AppendLine();
            output.AppendLine($"- **Mutation score:** {mutation.Score:0.0}%");
            output.AppendLine($"- **Killed:** {mutation.Killed}");
            output.AppendLine($"- **Survived:** {mutation.Survived}");
            output.AppendLine($"- **Timed out:** {mutation.TimedOut}");
            output.AppendLine($"- **No coverage:** {mutation.NoCoverage}");
            output.AppendLine();
        }

        output.AppendLine("---");
        output.AppendLine("Generated by ABB.");

        return output.ToString();
    }
}
