using System;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ABB.Analyze.VisualStudio.Services;

internal static class TestCommandService
{
    public static bool IsApproved(
    string command)
    {
        string normalizedCommand =
            NormalizeCommand(command);

        if (string.IsNullOrWhiteSpace(normalizedCommand))
        {
            return false;
        }

        if (ContainsUnsafeShellCharacters(normalizedCommand))
        {
            return false;
        }

        string lower = normalizedCommand.ToLowerInvariant();

        return
            lower.StartsWith("dotnet test") ||
            lower.StartsWith("pytest") ||
            lower.StartsWith("python -m pytest");
    }

    public static string NormalizeCommand(
    string command)
    {
        if (string.IsNullOrWhiteSpace(command))
        {
            return string.Empty;
        }

        string[] commandParts =
            command.Split(
                new[]
                {
                ' ',
                '\t',
                '\r',
                '\n'
                },
                StringSplitOptions.RemoveEmptyEntries);

        return string.Join(
            " ",
            commandParts);
    }

    private static bool ContainsUnsafeShellCharacters(
        string command)
    {
        return
            command.Contains("&") ||
            command.Contains("|") ||
            command.Contains(">") ||
            command.Contains("<");
    }

    public static async Task<string> RunAsync(
    string command,
    string workingDirectory,
    CancellationToken cancellationToken)
    {
        string normalizedCommand =
            NormalizeCommand(command);

        if (!IsApproved(normalizedCommand))
        {
            throw new InvalidOperationException(
                "Only dotnet test and pytest commands generated by QUACK " +
                "can be executed.");
        }

        var startInfo = new ProcessStartInfo
        {
            FileName = "cmd.exe",
            Arguments = $"/d /s /c \"{normalizedCommand}\"",
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8
        };

        using var process = new Process
        {
            StartInfo = startInfo,
            EnableRaisingEvents = true
        };

        if (!process.Start())
        {
            throw new InvalidOperationException(
                "The test process could not be started.");
        }

        Task<string> standardOutputTask =
            process.StandardOutput.ReadToEndAsync();

        Task<string> standardErrorTask =
            process.StandardError.ReadToEndAsync();

        Task processExitTask =
            WaitAsync(process);

        Task timeoutTask =
            Task.Delay(
                TimeSpan.FromMinutes(10),
                cancellationToken);

        Task completedTask =
            await Task.WhenAny(
                processExitTask,
                timeoutTask);

        if (cancellationToken.IsCancellationRequested)
        {
            TryKillProcess(process);

            cancellationToken.ThrowIfCancellationRequested();
        }

        if (completedTask != processExitTask)
        {
            TryKillProcess(process);

            throw new TimeoutException(
                "The test command exceeded the 10-minute timeout.");
        }

        await processExitTask;

        string standardOutput =
            await standardOutputTask;

        string standardError =
            await standardErrorTask;

        return BuildTestResult(
            normalizedCommand,
            process.ExitCode,
            standardOutput,
            standardError);
    }

    private static string BuildTestResult(
    string command,
    int exitCode,
    string standardOutput,
    string standardError)
    {
        bool noTestsMatched =
            standardOutput.IndexOf(
                "No test matches the given testcase filter",
                StringComparison.OrdinalIgnoreCase) >= 0;

        var result = new StringBuilder();

        result.AppendLine(
            $"Command: {command}");

        result.AppendLine(
            $"Exit code: {exitCode}");

        if (noTestsMatched)
        {
            result.AppendLine(
                "Result: No tests matched the generated filter.");
        }
        else if (exitCode == 0)
        {
            result.AppendLine(
                "Result: Test execution completed successfully.");
        }
        else
        {
            result.AppendLine(
                "Result: Test execution failed.");
        }

        result.AppendLine();

        if (!string.IsNullOrWhiteSpace(standardOutput))
        {
            result.AppendLine(
                standardOutput.TrimEnd());
        }

        if (!string.IsNullOrWhiteSpace(standardError))
        {
            result.AppendLine();
            result.AppendLine("Error output:");
            result.AppendLine(
                standardError.TrimEnd());
        }

        return result.ToString();
    }

    private static void TryKillProcess(
        Process process)
    {
        try
        {
            if (!process.HasExited)
            {
                process.Kill();
            }
        }
        catch
        {
            // Do not hide the timeout or cancellation error
            // when process cleanup fails.
        }
    }

    private static Task WaitAsync(Process process)
    {
        var source = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
        process.Exited += (_, _) => source.TrySetResult(null);
        if (process.HasExited) source.TrySetResult(null);
        return source.Task;
    }
}

